services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: urlshortener_dev
      POSTGRES_PORT: 5432
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  urlshortener:
    build: .
    container_name: urlshortener_container
    image: urshorterer:latest
    ports:
      - "8080:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/urlshortener_dev
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_PROFILES_ACTIVE: dev

volumes:
  pgdata: